#!/usr/bin/env ruby -W0
# install
# installs a theme (MAC OS X ONLY)
#
# Created by Gregory D. Stula on 1/8/16
# Copyright © 2016 Gregory D. Stula
#
# See LICENCE for more info 

unless `uname -a`.split(" ").first != "Darwin"

  name = 
     "molokai"
  source = 
     "https://raw.githubusercontent.com/gregstula/molokai-for-xcode/master/molokai.dvtcolortheme"

  path = 
     "#{ENV['HOME']}/Library/Developer/Xcode/UserData/FontAndColorThemes"

  `mkdir -p #{path}` unless File.directory?(path)
  `curl -# #{source} -o #{path}/#{name}.dvtcolortheme`
  puts "molokai.dvtcolortheme was successfully installed."
  puts "You may need to restart Xcode for changes to take effect."

end

