#!/usr/bin/env ruby -W0
# install
# installs a theme (MAC OS X ONLY)
#
# Created by Gregory D. Stula on 1/8/16
# Copyright © 2016 Gregory D. Stula
#
# See LICENCE for more info 

if OS.mac?
 theme_url = "https://raw.githubusercontent.com/gregstula/molokai-for-xcode/master/molokai.dvtcolortheme"
 theme_name = "molokai"
 path_to_colors = "#{ENV['HOME']}/Library/Developer/Xcode/UserData/FontAndColorThemes"
 `mkdir -p #{path_to_colors}` unless File.directory?(path_to_colors)
 `url /pat/to/github/molokai.dvtcolortheme -o > #{path_to_colors}/#{theme_name}.dvtcolortheme`
end

